name = "give_me_some_name"
statics = "statics"
version = "0.1"
template_router = "router" # Default: router.py
api_router = "api_router" # Default: api_router.py
requirements = []
extra_block_settings = "settings"