name = "Example Block"
statics = "statics"
version = 0.1
template_router = "router" # Default: router.py
api_router = "api_router" # Default: api_router.py
requirements = ["requests"]
is_main = true
extra_block_settings = "settings"