name: Test Package

on:
  push:
    branches: [nightly]
  pull_request:
    branches: [main, nightly]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Test with pytest
        run: |
          pip install pytest
          pytest tests/test_cli.py tests/test_block_manager.py